import { NextResponse } from 'next/server';
import prisma from "@/prismaClient";


const keywords = [
    { id: 322496, name: 'action' },
    { id: 333087, name: 'action!' },
    { id: 197532, name: 'civil action' },
    { id: 273853, name: 'climate action' },
    { id: 18042, name: 'affirmative action' },
    { id: 280566, name: 'action adventure' },
    { id: 212864, name: 'killed in action' },
    { id: 217954, name: 'work actions' },
    { id: 219404, name: 'action hero' },
    { id: 286214, name: 'dark action' },
    { id: 173265, name: 'missing in action' },
    { id: 2586, name: 'externally controlled action' },
    { id: 6182, name: "citizens' action committee" },
    { id: 274978, name: 'action packed' },
    { id: 275266, name: 'cgi-live action hybrid' },
    { id: 9977, name: 'part live action' },
    { id: 247799, name: 'action comedy' },
    { id: 244317, name: 'social action' },
    { id: 245230, name: 'live action remake' },
    { id: 209220, name: 'live action and animation' },
    { id: 9840, name: 'romance' },
    { id: 212760, name: 'interspecies romance' },
    { id: 213429, name: 'interclass romance' },
    { id: 282984, name: 'slow burn romance' },
    { id: 283057, name: 'passion and romance' },
    { id: 219877, name: 'failed romance' },
    { id: 283172, name: 'internet romance' },
    { id: 284235, name: 'holiday romance' },
    { id: 284274, name: 'unexpected romance' },
    { id: 221882, name: 'gothic romance' },
    { id: 222963, name: 'old age romance' },
    { id: 223521, name: 'dark romance' },
    { id: 258262, name: 'chivalric romance' },
    { id: 188237, name: 'teenage romance' },
    { id: 233305, name: 'mature romance' },
    { id: 269027, name: 'there is no modern romance' },
    { id: 269719, name: 'high school romance' },
    { id: 271599, name: 'anti-romance' },
    { id: 193607, name: 'shipboard romance' },
    { id: 272698, name: 'christmas romance' },
];

const actors = [
    {
        id: 1182816,
        name: "Kimberly Alexander",
        originalName: "Kimberly Alexander",
        gender: 1,
        popularity: 33.4157,
        profilePath: "/tWLWD3KzPoqjHh8QhVvjSRXzlfQ.jpg"
    },
    {
        id: 976,
        name: "Jason Statham",
        originalName: "Jason Statham",
        gender: 2,
        popularity: 26.2112,
        profilePath: "/8FMhYekyLR4ibHQ9Kpuaqe4cVjL.jpg"
    },
    {
        id: 109513,
        name: "Alexandra Daddario",
        originalName: "Alexandra Daddario",
        gender: 1,
        popularity: 23.4044,
        profilePath: "/lh5zibQXYH1MNqkuX8TmxyNYHhK.jpg"
    },
    {
        id: 10990,
        name: "Emma Watson",
        originalName: "Emma Watson",
        gender: 1,
        popularity: 21.3029,
        profilePath: "/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg"
    },
    {
        id: 1190668,
        name: "Timothée Chalamet",
        originalName: "Timothée Chalamet",
        gender: 2,
        popularity: 20.109,
        profilePath: "/BE2sdjpgsa2rNTFa66f7upkaOP.jpg"
    },
    {
        id: 1522703,
        name: "Hande Erçel",
        originalName: "Hande Erçel",
        gender: 1,
        popularity: 19.2707,
        profilePath: "/jrUvWNqOpfDm3D0KhbuRwQOy8Nu.jpg"
    },
    {
        id: 64,
        name: "Gary Oldman",
        originalName: "Gary Oldman",
        gender: 2,
        popularity: 19.2631,
        profilePath: "/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg"
    },
    {
        id: 6384,
        name: "Keanu Reeves",
        originalName: "Keanu Reeves",
        gender: 2,
        popularity: 18.826,
        profilePath: "/8RZLOyYGsoRe9p44q3xin9QkMHv.jpg"
    },
    {
        id: 117642,
        name: "Jason Momoa",
        originalName: "Jason Momoa",
        gender: 2,
        popularity: 18.0197,
        profilePath: "/6dEFBpZH8C8OijsynkSajQT99Pb.jpg"
    },
    {
        id: 18277,
        name: "Sandra Bullock",
        originalName: "Sandra Bullock",
        gender: 1,
        popularity: 17.9998,
        profilePath: "/hPHGKPAWZ8gArYXMk225rrYPoyJ.jpg"
    },
    {
        id: 115440,
        name: "Sydney Sweeney",
        originalName: "Sydney Sweeney",
        gender: 1,
        popularity: 17.9373,
        profilePath: "/uDnIdU4KGjQg7liFvb9wnALvg95.jpg"
    },
    {
        id: 2680307,
        name: "Sebastian Eugene Hansen",
        originalName: "Sebastian Eugene Hansen",
        gender: 2,
        popularity: 17.9193,
        profilePath: "/40HNkoB3RKPMPgLhTyKQU6kG0sc.jpg"
    },
    {
        id: 2604515,
        name: "Emma Myers",
        originalName: "Emma Myers",
        gender: 1,
        popularity: 17.877,
        profilePath: "/xBJsFGAL3sOIxMUA0sMVEKKpAL4.jpg"
    },
    {
        id: 2164904,
        name: "Catalina Sopelana",
        originalName: "Catalina Sopelana",
        gender: 1,
        popularity: 17.863,
        profilePath: null
    },
    {
        id: 1245,
        name: "Scarlett Johansson",
        originalName: "Scarlett Johansson",
        gender: 1,
        popularity: 17.5054,
        profilePath: "/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg"
    },
    {
        id: 131264,
        name: "Christine Romeo",
        originalName: "Christine Romeo",
        gender: 1,
        popularity: 17.0317,
        profilePath: "/dn8S2TeEQQtebBhU0MRX2YxDRC4.jpg"
    },
    {
        id: 74568,
        name: "Chris Hemsworth",
        originalName: "Chris Hemsworth",
        gender: 2,
        popularity: 16.9412,
        profilePath: "/piQGdoIQOF3C1EI5cbYZLAW1gfj.jpg"
    },
    {
        id: 224513,
        name: "Ana de Armas",
        originalName: "Ana de Armas",
        gender: 1,
        popularity: 15.7096,
        profilePath: "/qvnPiNz9CKxgSwm93ZoSycjVg0M.jpg"
    },
    {
        id: 18897,
        name: "Jackie Chan",
        originalName: "成龍",
        gender: 2,
        popularity: 15.1602,
        profilePath: "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg"
    },
    {
        id: 12835,
        name: "Vin Diesel",
        originalName: "Vin Diesel",
        gender: 2,
        popularity: 15.1179,
        profilePath: "/nZdVry7lnUkE24PnXakok9okvL4.jpg"
    }
];

const movies = [
    {
        id: 324544,
        title: "In the Lost Lands",
        originalTitle: "In the Lost Lands",
        releaseDate: new Date("2025-02-27"),
        runtime: null,
        overview: "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where the sorceress and her guide, the drifter Boyce must outwit and outfight man and demon.",
        tagline: null,
        status: null,
        popularity: 727.9871,
        rating: 6.374,
        voteCount: 178,
        posterPath: "/iHf6bXPghWB6gT8kFkL1zo00x6X.jpg",
        backdropPath: "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 950387,
        title: "A Minecraft Movie",
        originalTitle: "A Minecraft Movie",
        releaseDate: new Date("2025-03-31"),
        runtime: null,
        overview: "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
        tagline: null,
        status: null,
        popularity: 673.4901,
        rating: 6.1,
        voteCount: 555,
        posterPath: "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
        backdropPath: "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1197306,
        title: "A Working Man",
        originalTitle: "A Working Man",
        releaseDate: new Date("2025-03-26"),
        runtime: null,
        overview: "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
        tagline: null,
        status: null,
        popularity: 646.3416,
        rating: 6.349,
        voteCount: 242,
        posterPath: "/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg",
        backdropPath: "/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1045938,
        title: "G20",
        originalTitle: "G20",
        releaseDate: new Date("2025-04-09"),
        runtime: null,
        overview: "After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.",
        tagline: null,
        status: null,
        popularity: 639.4622,
        rating: 6.537,
        voteCount: 217,
        posterPath: "/tSee9gbGLfqwvjoWoCQgRZ4Sfky.jpg",
        backdropPath: "/k32XKMjmXMGeydykD32jfER3BVI.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1195506,
        title: "Novocaine",
        originalTitle: "Novocaine",
        releaseDate: new Date("2025-03-12"),
        runtime: null,
        overview: "When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.",
        tagline: null,
        status: null,
        popularity: 488.1797,
        rating: 6.868,
        voteCount: 428,
        posterPath: "/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg",
        backdropPath: "/sNx1A3822kEbqeUxvo5A08o4N7o.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1293286,
        title: "Gunslingers",
        originalTitle: "Gunslingers",
        releaseDate: new Date("2025-04-11"),
        runtime: null,
        overview: "When the most wanted man in America surfaces in a small Kentucky town, his violent history -- and a blood-thirsty mob seeking vengeance and a king’s ransom -- soon follow. As brothers face off against one another and bullets tear the town to shreds, this lightning-fast gunslinger makes his enemies pay the ultimate price for their greed.",
        tagline: null,
        status: null,
        popularity: 448.398,
        rating: 6.765,
        voteCount: 17,
        posterPath: "/O7REXWPANWXvX2jhQydHjAq2DV.jpg",
        backdropPath: "/zksO4lVnRKRoaSYzh2EDn2Z3Pel.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 822119,
        title: "Captain America: Brave New World",
        originalTitle: "Captain America: Brave New World",
        releaseDate: new Date("2025-02-12"),
        runtime: null,
        overview: "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
        tagline: null,
        status: null,
        popularity: 357.1556,
        rating: 6.131,
        voteCount: 1391,
        posterPath: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
        backdropPath: "/ce3prrjh9ZehEl5JinNqr4jIeaB.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1125899,
        title: "Cleaner",
        originalTitle: "Cleaner",
        releaseDate: new Date("2025-02-19"),
        runtime: null,
        overview: "When a group of radical activists take over an energy company's annual gala, seizing 300 hostages, an ex-soldier turned window cleaner suspended 50 storeys up on the outside of the building must save those trapped inside, including her younger brother.",
        tagline: null,
        status: null,
        popularity: 193.8037,
        rating: 6.531,
        voteCount: 207,
        posterPath: "/mwzDApMZAGeYCEVjhegKvCzDX0W.jpg",
        backdropPath: "/gsQJOfeW45KLiQeEIsom94QPQwb.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1229730,
        title: "Carjackers",
        originalTitle: "Carjackers",
        releaseDate: new Date("2025-03-27"),
        runtime: null,
        overview: "By day, they're invisible—valets, hostesses, and bartenders at a luxury hotel. By night, they're the Carjackers, a crew of skilled drivers who track and rob wealthy clients on the road. As they plan their ultimate heist, the hotel director hires a ruthless hitman, to stop them at all costs. With danger closing in, can Nora, Zoe, Steve, and Prestance pull off their biggest score yet?",
        tagline: null,
        status: null,
        popularity: 169.7769,
        rating: 6.24,
        voteCount: 127,
        posterPath: "/wbkPMTz2vVai7Ujyp0ag7AM9SrO.jpg",
        backdropPath: "/is9bmV6uYXu7LjZGJczxrjJDlv8.jpg",
        homepage: null,
        originalLang: "fr",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1244944,
        title: "The Woman in the Yard",
        originalTitle: "The Woman in the Yard",
        releaseDate: new Date("2025-03-27"),
        runtime: null,
        overview: "In the aftermath of her husband's death, widow Ramona's struggle to raise her two kids is hindered by the arrival of a mysterious woman with supernatural abilities.",
        tagline: null,
        status: null,
        popularity: 172.9102,
        rating: 6.27,
        voteCount: 37,
        posterPath: "/n0WS2TsNcS6dtaZKzxipyO7LuCJ.jpg",
        backdropPath: "/3lEV4CoKoeT2cZ4fbKEJugZcw6Z.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1353117,
        title: "Home Sweet Home: Rebirth",
        originalTitle: "Home Sweet Home: Rebirth",
        releaseDate: new Date("2025-03-20"),
        runtime: null,
        overview: "When a city is overrun with a demonically-possessed crowd, a cop must find the source of evil to save his family.",
        tagline: null,
        status: null,
        popularity: 172.3625,
        rating: 7.096,
        voteCount: 26,
        posterPath: "/9rCBCm9cyI4JfLEhx3EncyncMR3.jpg",
        backdropPath: "/wmqpE7p2dUCEgCnovuovoNXaCXr.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 696506,
        title: "Mickey 17",
        originalTitle: "Mickey 17",
        releaseDate: new Date("2025-02-28"),
        runtime: null,
        overview: "Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.",
        tagline: null,
        status: null,
        popularity: 161.0623,
        rating: 6.9,
        voteCount: 1529,
        posterPath: "/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg",
        backdropPath: "/hNA73rnG4PjSwgojaC2gbO1f8Rt.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 1373723,
        title: "The Codes of War",
        originalTitle: "The Codes of War",
        releaseDate: new Date("2025-03-20"),
        runtime: null,
        overview: "War stories about family, ethics and honor include the true story of two U.S. Marines who in a span of six seconds, must stand their ground to stop a suicide truck bomb, a Navy Corpsman who attempts to hold on to his humanity, and a WW2 soldier who gets separated from his squad and is forced to re-evaluate his code.",
        tagline: null,
        status: null,
        popularity: 144.9178,
        rating: 6.3,
        voteCount: 54,
        posterPath: "/oXeiQAfRK90pxxhP5iKPXQqAIN1.jpg",
        backdropPath: "/ibF5XVxTzf1ayzZrmiJqgeQ39Qk.jpg",
        homepage: null,
        originalLang: "en",
        budget: null,
        revenue: null,
        createdAt: new Date(),
        updatedAt: new Date()
    }
];

export async function POST() {
    try {
        await prisma.keyword.createMany({
            data: keywords,
            skipDuplicates: true,
        });

        await prisma.actor.createMany({
            data: actors,
            skipDuplicates: true,
        });

        await prisma.movie.createMany({
            data: movies,
            skipDuplicates: true,
        });

        return NextResponse.json({ message: 'Init completed' });
    } catch (error) {
        console.error(error);
        return NextResponse.json({ error: 'Something went wrong' }, { status: 500 });
    }
}
